spring:
  application:
    name: RelatedArticles-Service

server:
  port: ${PORT:8088}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




  instance:
    instance-id: RelatedArticles-1
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false
    
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
        