spring:
  application:
    name: RelatedArticles-Service

server:
  port: ${PORT:8088}


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.8:8761/eureka




  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.9
    instance-id: RelatedArticles-1
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false