spring:
   application:
      name: Rating-Service
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
     
server:
  port: ${PORT:8099}
  
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.43.81:8761/eureka

    instance:
      prefer-ip-address: true
      ip-address: 192.168.43.41
      instance-id: Rate-3
      metadataMap:
        zone: zone3


endpoints:
  shutdown:
    enabled: true
    sensitive: false