spring:
   application:
      name: Rate-Service
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
     
server:
  port: ${PORT:8080}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


  instance:
    instance-id: Rate-1
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false