spring:
   application:
      name: Rating-Service
   rabbitmq:
     host: 192.168.1.8
     port: 5672
     username: test
     password: test
     
server:
  port: ${PORT:8099}
  
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.1.8:8761/eureka

    instance:
      prefer-ip-address: true
      ip-address: 192.168.1.8
      instance-id: Rate-3
      metadataMap:
        zone: zone3


endpoints:
  shutdown:
    enabled: true
    sensitive: false