spring:
   application:
      name: Rate-Service
   rabbitmq:
     host: 192.168.1.8
     port: 5672
     username: test
     password: test
     
server:
  port: ${PORT:8080}


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.8:8761/eureka


  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.9
    instance-id: Rate-1
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false