spring:
   application:
      name: Zull-Gatway

server:
  port: ${PORT:8085}
      
eureka:
    client:
        serviceUrl:
            defaultZone: http://172.20.10.2:8761/eureka
        registerWithEureka: false
        preferSameZoneEureka: true
    instance:
      prefer-ip-address: true
      ip-address: 172.20.10.2
      metadataMap:
            zone: zone3
    
        
zuul:
   prefix: /api
   routes:
      Articles-Service:
        path: /Articles/**
        serviceId: Articles-Service
      Comments-Service:
        path: /Comments/**
        serviceId: Comments-Service
      Search-Service:
        path: /Search/**
        serviceId: Search-Service
      Rating-Service:
        path: /Rating/**
        serviceId: Rating-Service
ribbon: 
   eureka:
      enabled: true