spring:
   application:
      name: Articles-Service
   rabbitmq:
     host: 127.0.0.1
     port: 5672
     dynamic: true
     username: guest
     password: guest
     
server:
  port: ${PORT:9999}
  
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.43.81:8761/eureka
    instance:
      prefer-ip-address: true
      ip-address: 192.168.43.41
      instance-id: Article-3
      metadataMap:
            zone: zone3
  
endpoints:
   shutdown:
      enabled: true
      sensitive: false

  

  