spring:
   application:
      name: Articles-Service
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
   zipkin: 
      rabbitmq:
         addresses: http://localhost:15672    
         queue: ArticleIdToComments
  
       
     
server:
  port: ${PORT:9070}
  
  
eureka:
  client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
            
  instance:
    instance-id: Articles-1
    metadataMap:
      zone: zone1
      
  
endpoints:
   shutdown:
      enabled: true
      sensitive: false
   

management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
        

zipkin:
   base-url: http://localhost:9411/          
        
   