spring:
   application:
      name: discovery-service
      
server:
  port: ${PORT:8761}
   
eureka:
  instance:
      instance-id: discovery-4
      metadataMap:
            zone: zone4
  client:
      serviceUrl:
         registerWithEureka: false
         fetchRegistry: false
    
endpoints:
   shutdown:
      enabled: true
      sensitive: false 