spring:
   application:
      name: Comments-Service
   rabbitmq:
     host: 172.20.10.2
     port: 5672
     username: test
     password: test
     
server:
  port: ${PORT:8082}
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.20.10.2:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 172.20.10.2
    instance-id: Comment-3
    metadataMap:
      zone: zone3

endpoints:
  shutdown:
    enabled: true
    sensitive: false
