spring:
   application:
      name: Comments-Service
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
     
server:
  port: ${PORT:8060}
  
  
eureka:
  client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
            
  instance:
    instance-id: Comments-1
    metadataMap:
      zone: zone1
            
endpoints:
  shutdown:
    enabled: true
    sensitive: false
