spring:
   application:
      name: Comments-Service
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
     
server:
  port: ${PORT:8082}
  
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      ip-address: 192.168.43.245
      instance-id: Comment-4
      metadataMap:
            zone: zone4
  
endpoints:
   shutdown:
      enabled: true
      sensitive: false