spring:
   application:
      name: Search-Service
     
server:
  port: ${PORT:8084}
  
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.43.81:8761/eureka
    instance:
      prefer-ip-address: true
      ip-address: 192.168.43.245
      instance-id: Search-4
      metadataMap:
            zone: zone4
  
endpoints:
   shutdown:
      enabled: true
      sensitive: false