spring:
   application:
      name: Search-Service
     
server:
  port: ${PORT:8084}
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.8:8761/eureka
            
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.9
    instance-id: Search-1
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false