spring:
   application:
      name: Search-Service
     
server:
  port: ${PORT:8084}
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
            
  instance:
    metadataMap:
      zone: zone1


endpoints:
  shutdown:
    enabled: true
    sensitive: false
    
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
        
zipkin:
   base-url: http://localhost:9411/        
        